# NLP_phishing_detection_Project - Configuration Logging
# Auteur: Souleymane Sall
# Email: sallsouleymane2207@gmail.com

default:
  # Niveau de logging
  level: ${oc.env:LOG_LEVEL,INFO}
  
  # Format de logging
  format: ${oc.env:LOG_FORMAT,json}  # json ou text
  
  # Handlers
  handlers:
    console:
      enabled: true
      level: INFO
    file:
      enabled: true
      level: DEBUG
      filename: logs/app.log
      max_bytes: 10485760  # 10MB
      backup_count: 5
  
  # Loggers spécifiques
  loggers:
    uvicorn:
      level: INFO
    mlflow:
      level: WARNING
    optuna:
      level: INFO